version: '3.9'
services:
  db:
    image: postgres:15
    container_name: db_daixatu
    env_file: 
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: redis_daixatu

 
  
  celery:
    build:
      context: .
    container_name: celery_daixatu
    command: ["/xatu/docker/celery.sh"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

    
    

